Incorrectly documented use of `orderbook` method.
Docs would lead you to do:

```ruby
client.orderbook(ORDER_BOOK_TYPE, level: ORDER_BOOK_LEVEL)" #=>
ArgumentError: wrong number of arguments (given 2, expected 0..1)
```

But instead, you need to initialize the client with ORDER_BOOK_TYPE (as is described in the docs):

```ruby
Coinbase::Exchange::Client.new(
  ENV['CB_API_KEY'],
  ENV['CB_API_SECRET'],
  ENV['CB_PASSPHRASE'],
  product_id: ORDER_BOOK_TYPE
)
```